import spain from '../../../Assets/Icons/spain.svg';
// import engl from '../../../Assets/Icons/english.svg';
// import china from '../../../Assets/Icons/china.svg';
// import german from '../../../Assets/Icons/german.svg';
// import ICoursesList from '../../../Types/courses-list-types';
import { ROUTES_COURSE } from '../Routes/routes';

// export const coursesList: ICoursesList[] = [
//   {
//     logo: `${engl}`,
//     title: 'Англійська для початкового рівня',
//     duration: '30 годин',
//     modules: '3',
//     details: 'Дізнатись детальніше',
//     price: 'Від 2000 грн',
//     color: 'course__blue',
//     link: ROUTES_COURSE.engEasy,
//     lessons: '30',
//     task: '240',
//     tests: '10',
//     expert: '8',
//   },
//   {
//     logo: `${engl}`,
//     title: 'Англійська для середнього рівня',
//     duration: '45 годин',
//     modules: '4',
//     details: 'Дізнатись детальніше',
//     price: 'Від 3500 грн',
//     color: 'course__blue',
//     link: ROUTES_COURSE.engMiddle,
//     lessons: '36',
//     task: '320',
//     tests: '20',
//     expert: '5',
//   },
//   {
//     logo: `${engl}`,
//     title: 'Англійська для високого рівня',
//     duration: '35 годин',
//     modules: '5',
//     details: 'Дізнатись детальніше',
//     price: 'Від 2500 грн',
//     color: 'course__blue',
//     link: ROUTES_COURSE.engHigh,
//     lessons: '30',
//     task: '300',
//     tests: '35',
//     expert: '15',
//   },
//   {
//     logo: `${german}`,
//     title: 'Німецька для початкового рівня',
//     duration: '30 годин',
//     modules: '3',
//     details: 'Дізнатись детальніше',
//     price: 'Від 2000 грн',
//     color: 'course__orange',
//     link: ROUTES_COURSE.germanEasy,
//     lessons: '30',
//     task: '240',
//     tests: '10',
//     expert: '8',
//   },
//   {
//     logo: `${german}`,
//     title: 'Німецька для середнього рівня',
//     duration: '45 годин',
//     modules: '5',
//     details: 'Дізнатись детальніше',
//     price: 'Від 3500 грн',
//     color: 'course__orange',
//     link: ROUTES_COURSE.germanMiddle,
//     lessons: '36',
//     task: '320',
//     tests: '20',
//     expert: '5',
//   },
//   {
//     logo: `${german}`,
//     title: 'Німецька для високого рівня',
//     duration: '40 годин',
//     modules: '4',
//     details: 'Дізнатись детальніше',
//     price: 'Від 3000 грн',
//     color: 'course__orange',
//     link: ROUTES_COURSE.germanHigh,
//     lessons: '30',
//     task: '300',
//     tests: '35',
//     expert: '15',
//   },
//   {
//     logo: `${spain}`,
//     title: 'Іспанська для початкового рівня',
//     duration: '35 годин',
//     modules: '3',
//     details: 'Дізнатись детальніше',
//     price: 'Від 2000 грн',
//     color: 'course__green',
//     link: ROUTES_COURSE.spainEasy,
//     lessons: '28',
//     task: '305',
//     tests: '36',
//     expert: '13',
//   },
//   {
//     logo: `${spain}`,
//     title: 'Іспанська для середнього рівня',
//     duration: '45 годин',
//     modules: '5',
//     details: 'Дізнатись детальніше',
//     price: 'Від 3500 грн',
//     color: 'course__green',
// link: ROUTES_COURSE.spainMiddle,
//     lessons: '25',
//     task: '200',
//     tests: '14',
//     expert: '7',
//   },
//   {
//     logo: `${spain}`,
//     title: 'Іспанська для високого рівня',
//     duration: '60 годин',
//     modules: '7',
//     details: 'Дізнатись детальніше',
//     price: 'Від 4500 грн',
//     color: 'course__green',
//     link: ROUTES_COURSE.spainHigh,
//     lessons: '28',
//     task: '160',
//     tests: '15',
//     expert: '5',
//   },
//   {
//     logo: `${china}`,
//     title: 'Китайська для початкового рівня',
//     duration: '50 годин',
//     modules: '7',
//     details: 'Дізнатись детальніше',
//     price: 'Від 4500 грн',
//     color: 'course__red',
//     link: ROUTES_COURSE.chinaEasy,
//     lessons: '24',
//     task: '240',
//     tests: '55',
//     expert: '13',
//   },
//   {
//     logo: `${china}`,
//     title: 'Китайська для середнього рівня',
//     duration: '40 годин',
//     modules: '4',
//     details: 'Дізнатись детальніше',
//     price: 'Від 3500 грн',
//     color: 'course__red',
//     link: ROUTES_COURSE.chinaMiddle,
//     lessons: '18',
//     task: '260',
//     tests: '30',
//     expert: '9',
//   },
//   {
//     logo: `${china}`,
//     title: 'Китайська для високого рівня',
//     duration: '75 годин',
//     modules: '5',
//     details: 'Дізнатись детальніше',
//     price: 'Від 5500 грн',
//     color: 'course__red',
//     link: ROUTES_COURSE.chinaHigh,
//     lessons: '30',
//     task: '300',
//     tests: '35',
//     expert: '15',
//   },
// ];
